services:
  tulink-backend-development:
    container_name: tulink-backend-development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    networks:
      - tulink-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
    depends_on:
      tulink-redis-development:
        condition: service_healthy
    command: npm run start:dev

  tulink-redis-development:
    container_name: tulink-redis-development
    image: redis:6-alpine
    env_file:
      - .env.development
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - tulink-network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tulink-network:
    driver: bridge
